### PR TITLE
Fixes for Zig 0.10.1

### PR DESCRIPTION
**Pull request by anacrolix**
I'm a total Zig noob, but took a look at your library to try it out and updated it for Zig 0.10.1. The bencode_to_yaml.zig examples now work, and the tests pass with `zig build test`.

I'm not sure about the tidiest way to handle the expect* functions (after they newly require I assume) to return errors. I just patched it up as quickly as I could, I can make this more consistent.

One part of the code I'm completely unsure about is stringifying unions. I did my best and it passes tests, I don't know if there is one for that case.

It's probably a lot better than it was before (it actually compiles and runs).

### CODE REVIEW

**Comment by gaultier** [comment]
Hey, thanks for the PR, I will have a look as a soon as I can, it might take a few days.

**Comment by anacrolix** [comment]
Thanks

**Comment by anacrolix** [comment]
Any update? Cheers

**Comment by gaultier** [comment]
Sorry to have taken so long.
I realize my current life situation does not allow me to dedicate the proper time to support contributions.
I suggest to fork and apply the changes there; again, sorry to have taken so long to come to this realization.

**Comment by anacrolix** [comment]
No worries at all, completely understandable. Thanks for letting me know!

**Comment by anacrolix** [comment]
I've documented my fork and included a link to reasoning here. https://github.com/anacrolix/zig-bencode.

**Comment by gaultier** [comment]
Thanks, mentioned in the README in this project.

**Pull request closed without merging**
